[theme]
# Gruvbox Theme
# background = "default"
# primary = "#a89984"
# secondary = "#928374"
# title = "#8ec07c"
# playing = "#689d6a"
# playing_bg = "#383838"
# playing_selected = "#ebdbb2"
# highlight = "#d5c4a1"
# highlight_bg = "#484848"
# error = "#fbf1c7"
# error_bg = "#cc241d"
# statusbar_progress = "#458588"
# statusbar_bg = "#282828"
# statusbar = "#98971a"
# cmdline = "#d5c4a1"
# cmdline_bg = "#383838"
# search_match = "#fabd2f"

# Catppuccin Theme
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#94e2d5"
title = "#b4befe"
playing = "#a6e3a1"
playing_bg = "#1e1e2e"
highlight = "#cdd6f4"
highlight_bg = "#696e96"
playing_selected = "#a6e3a1"
error = "#1e1e2e"
error_bg = "#f38ba8"
statusbar = "#b4befe"
statusbar_bg = "#313244"
statusbar_progress = "#b4befe"
cmdline = "#b4befe"
cmdline_bg = "#181825"
